//LOGIN AND LOGOUT
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

//CLIENTES 
export const FILL_CLIENTES = "FILL_CLIENTES";
export const SELECT_CLIENTE = "SELECT_CLIENTE";
export const SELECT_DIRECCION_CLIENTE = "SELECT_DIRECCION_CLIENTE";

//GRUPO DE  CLIENTES 
export const FILL_GRUPOS_CLIENTE = "FILL_GRUPOS_CLIENTE";
export const SELECT_GRUPO_CLIENTE = "SELECT_GRUPO_CLIENTE";

//PRODUCTOS DE TIENDA
export const FILL_PRODUCTS = "FILL_PRODUCTS";

//PROFESIONES
export const FILL_PROFESIONES = "FILL_PROFESIONES";
export const SELECT_PROFESION = "SELECT_PROFESION";

//ROLES
export const FILL_ROLES = "FILL_ROLES";
export const SELECT_ROL = "SELECT_ROL";

//TIPO DE DOCUMENTOS
export const FILL_TIPOS_DOCUMENTO = "FILL_TIPOS_DOCUMENTO";
export const SELECT_TIPO_DOCUMENTO = "SELECT_TIPO_DOCUMENTO";

//PARA LA PAGINA DE USUARIOS
export const FILL_TABLE_USERS = "FILL_TABLE_USERS";
export const SELECT_USER = "SELECT_USER";

//CRUD
export const CREATE_DATA = "CREATE_DATA";
export const READ_ALL_DATA = "READ_ALL_DATA";
export const UPDATE_DATA = "UPDATE_DATA";
export const DELETE_DATA = "DELETE_DATA";
export const NO_DATA = "NO_DATA";